version: 2.1

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

jobs:
  e2e:
    executor: with-chrome
    steps:
      - checkout
      - run: echo "Private Orb Change 1"
      - run: ./node_modules/.bin/cypress install
      - run:
          name: Run Cypress Tests
          command: |
            npx cypress run \
            --config baseUrl=https://rails-signup-thankyou-boh.herokuapp.com/ \
            --browser firefox \
            --reporter junit \
            --reporter-options "mochaFile=results/my-test-output-[hash].xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
